# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Generate

on:
  workflow_dispatch:
    inputs:
      sheetname:
        description: 'Sheet Name'
        required: true
      spreadsheetid:
        description: 'SpreadSheet Id'
        required: false
        default: '15pV0dVEnY-aHxrI9elsx7JlajG8Phu5oJVGqBYGDJHk'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
          sheetname: ${{ github.event.inputs.sheetname }}
          spreadsheetid: ${{ github.event.inputs.spreadsheetid }}
          apiKey: ${{ secrets.API_KEY }}
        run: npm run generate:upload
